version: '3.1'

services:
  workoutapp-frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    # networks:
    #   - frontend

# networks:
#   frontend:
#     name: workoutapp-frontend-network
#     external: true
