import Head from "next/head";

function Home() {
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js</a> starter!
        </h1>
        <h2>Features:</h2>
        <ul>
          <li>global stylesheet</li>
          <li>project directory layout</li>
          <li>material ui</li>
          <li>navigation drawer</li>
        </ul>
      </main>
    </div>
  );
}

export { Home };
